export enum AuthActionsType {
  LOGIN_SUCCESS = 'LOGIN_SUCCESS',
  LOGIN_FAILED = 'LOGIN_FAILED',

  SIGN_UP_LOADING = 'SIGN_UP_LOADING',
  SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS',
  SIGN_UP_FAILED = 'SIGN_UP_FAILED',

  LOGOUT = 'LOGOUT',
  LOGOUT_LOADING = 'LOGOUT_LOADING',
}
